### ISSUE TITLE
[tableView reloadData] not update images

### ISSUE THREAD

**Issue by LunevNF** [agusso/ASOXScrollTableViewCell#14]
Hello.
When I try to reload table with new data (new images), xScrollViewCell shows me previous image, but if I scroll horizontalView at row of table and after scroll back image are update. 
When tableView loads first time, all images visible normal. Bug after only reloadData.
Question: how to update all images after [tableView reloadData]?

**first load:**
![d70bbe7ec51b4277baa9ecad84693093](https://cloud.githubusercontent.com/assets/15741303/19618596/807c04dc-9879-11e6-9823-b6fab3508b9a.png)

**reloadData:**
![121212](https://cloud.githubusercontent.com/assets/15741303/19618613/ece9c938-9879-11e6-862e-bc19ae0ef1b1.png)

**after scroll first row (updated hidden by scrolling image):**
![23232](https://cloud.githubusercontent.com/assets/15741303/19618631/293e2cd0-987a-11e6-824c-4276a311b619.png)

**Comment by LunevNF** [comment]
> (UICollectionViewCell *)horizontalScrollContentsView:(UICollectionView *)horizontalScrollContentsView cellForItemAtContentIndexPath:

called after some numbers of call (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
This number of calls different for all different new data.

**Comment by LunevNF** [comment]
So, cellForRowAtIndexPath may called 2 times and cellForItemAtContentIndexPath not called even one time.

**Comment by LunevNF** [comment]
Why table with ASOX repeating some old rows (cached images from some old rows)?

**Comment by agusso** [comment]
Hi there,

You need to do reloadData of the horizontalScrollContentsView belongs to the ASOXScrollTableViewCell instance.
e.g.
To reloadData of horizontal items in tableView section 0 row 0

`ASOXScrollTableViewCell *aCell = (ASOXScrollTableViewCell *)[self.tableView cellForRowAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:0]];
UICollectionView *xScrollContentsView = [aCell horizontalScrollContentsView];
[xScrollContentsView reloadData];`

**Comment by LunevNF** [comment]
No, your example not worked properly. With image async download or without it program goes to cycle and error crash.

Thanks for answer, I already resolve this problem yesterday. And with reload data.
So, I insert `[self.horizontalScrollContentsView reloadData];` to `- (void)layoutSubviews` of `ASOXScrollTableViewCell.m`. This helps me, but images redownloads (rows count of table = redownload).
